#!/usr/bin/python

import sys

e = 65537
n = 4966306421059967
p = 67867967
q = n/p

print p
print q


for i in range(3,10):
	if(n % i == 0):
		print i
		break
	i = i + 2

totient = (p - 1)*(q - 1)

print totient

d = 3627069957225473

for i in range(1, 10):
	if(((i * totient) + 1) % e == 0):
		d = ((i * totient) + 1)/e
		print d

print ((e * d) % totient)

print n
print q*p

print hex(d)
 
